### ISSUE TITLE
small fix for "ocean" use

### ISSUE THREAD

**Issue by Luis122002** [CristianQiu/Unity-URP-Volumetric-Light#3]
Hello, using the package it seems that a property is missing that defines the rendering limit below, it was mentioned that it does not have support for transparent objects, which could take measures for glass, but for water or the ocean it is already a problem If possibly the package is adjusted to make fog and it manages to affect the "depht" property of the water, a quick solution that I could do is in the shader code "VolumetricFog.shader" add a global float value in my case called "_LimitGround" and The only change made would be this code:

 float GetFogDensity(float posWSy)
 {

     if (posWSy < _LimitGround)
     {
         return 0.0;
     }

     float t = saturate((posWSy - _BaseHeight) / (_MaximumHeight - _BaseHeight));
     t *= t;
     t = 1.0 - t;

     return _Density * t;
 }
 
 ![imagen](https://github.com/user-attachments/assets/7dd8133f-af86-49a0-b72b-e4b21f9b5c9b)
 
 The left image is the depth problem you mention, and the right is already using the value limited to the height of the ocean.
 It would be good to use that value as a property of the "volume" component.

**Comment by CristianQiu** [comment]
Hey, thanks for the feedback. I'll think about a nicer way to add this. It is a bit specific scenario that most users may not need, but it certainly has its use. Additionally, some extra computations could be skipped when below the defined plane, so that is some extra performance as well.

**Comment by CristianQiu** [comment]
Hey, I just added this in version 0.3.0 along with a couple of changes more. It is under the "Ground" section in the volume component.
