### ISSUE TITLE
bug due to use of soft shadows with local volumetric lighting

### ISSUE THREAD

**Issue by Luis122002** [CristianQiu/Unity-URP-Volumetric-Light#4]
Hello again, while working to find better performance for my project, I discovered that the package has a problem with the use of forward and deferred rendering when using smoothed shadows in medium or high quality.

It may not matter much since forward+ works perfectly and it's possibly the same case with deferred+ for unity 6, but the route that at least got to this point was to choose forward or deferred, use soft shadows in medium or high quality and have the option "Enable additional light contribution" marked and in the part where the error arises, is when using the shader pressure mod in "unified", the probability of using this is very low, but yes, that can happen.

![imagen](https://github.com/user-attachments/assets/469c9da3-3d65-48ff-8563-d30f7de080f0)
In the image on the left I use medium quality soft shadows, and on the right I use low quality soft shadows.

**Comment by CristianQiu** [comment]
Hi, 

I made a quick test and could not reproduce this. What I find weird in your image is that what appear to be NaNs, are not even close to the brightest part of the sun. 

You mention that it only happens when additional lights contribution is enabled, right? Do you have additional lights in the black patches of the left image? There seems to be a point light far away in the right image but I cannot see any other light other than the sun.

Which version of Unity are you using, btw? I tried to reproduce it on 6.0.18.

**Comment by Luis122002** [comment]
I use unity 6.20f1 but it is a bug that is somewhat complicated or very unlikely to appear, according to the settings I made it is in "player" -> "shader precision mode" [unified], in rendering settings for shadows, it is used in " medium" or "hight" and the "additional lights contribution" is enabled

![Testing    Assets   Windows, Mac, Linux   Unity 6 Preview (6000020f1) _DX11_ 2024 10 18 12 30 48](https://github.com/user-attachments/assets/44f3ceb7-32df-4d26-abf2-d10fd92046cf)

**Comment by CristianQiu** [comment]
Hey,

Just wanted to mention that I was just able to reproduce this by replicating most of your settings, not sure why I did not see it before. I'll have a look when I can.

**Comment by CristianQiu** [comment]
Hey, here goes a bit of technical info about this issue for the future:

It seems that when sampling outside the additional light shadowmap during raymarching, using Unity's "AdditionalLightRealtimeShadow" function from "com.unity.render-pipelines.universal\ShaderLibrary\Shadows.hlsl" NaNs are coming through.

If you add the last two lines from the following code to VolumetricFog.shader, around line 100, it should patch the problem.

![NaNFix](https://github.com/user-attachments/assets/488b3717-017c-4701-b9db-6d0316c2ed1e)

I'm not sure if I'll end up adding something to be able to stop these NaNs for this particular case, like with another check from the volume.

**Comment by Luis122002** [comment]
yes, it works fine with that setting
