### ISSUE TITLE
Openupm Support

### ISSUE THREAD

**Issue by AtaTrkgl** [CristianQiu/Unity-URP-Volumetric-Light#9]
This package is really great and could benefit from [openupm](https://openupm.com/). To be able to integrate the package to openupm, git tags with semantic versioning is required. If you could create a tag and release for the current version (currently: `0.3.6`), this repo can be added to openupm.

**Comment by CristianQiu** [comment]
I just added it, let me know if there is any issue ;) !

**Comment by AtaTrkgl** [comment]
Thank you! I've left the URL to this package on OpenUPM below. I think it matches the versions there via git tags so you'll have to create a new tag for each new version.

[OpenUPM URL](https://openupm.com/packages/com.cqf.urpvolumetricfog/)
